# -*- coding: utf-8 -*-
T_YEAR = 104
C_TERM = 1

week_dict = {'M': 'a', 'T': 'b', 'W': 'c', 'R': 'd', 'F': 'e', 'S': 'f', 'U': 'g'}

course_dict = {'1': 'a','2': 'b','3': 'c','4': 'd','N': 'e','5': 'f','6': 'g','7': 'h','8': 'i','9': 'j','A': 'k','B': 'l','C': 'm', 'D': 'n'}

DEPT_CHOICE = (('', '開課單位 Choose the course offering department'),
                    ('A2','A2  -  體育室           OPE'),
                    ('A3','A3  -  軍訓室           MT'),
                    ('A4','A4  -  師培中心         CTE'),
                    ('A5','A5  -  計網中心         CN'),
                    ('A6','A6  -  服務學習         SS'),
                    ('AA','AA  -  共同英授'),
                    ('AH','AH  -  華語中心         CLC'),
                    ('AN','AN  -  學士學程         CCEP'),
                    ('C0','C0  -  科學班'),
                    ('A1','A1  -  外國語言         FLL'),
                    ('A7','A7  -  基礎國文         CL'),
                    ('A9','A9  -  通識中心         GE'),
                    ('AG','AG  -  公民歷史'),
                    ('B1','B1  -  中文系           CL'),
                    ('B2','B2  -  外文系           FLL'),
                    ('B3','B3  -  歷史系           HIS'),
                    ('B5','B5  -  台文系           TWL'),
                    ('C1','C1  -  數學系           MATH'),
                    ('C2','C2  -  物理系           PHYS'),
                    ('C3','C3  -  化學系           CHEM'),
                    ('C4','C4  -  地科系           EARS'),
                    ('F8','F8  -  光電系           DPS'),
                    ('E0','E0  -  工學院           COE'),
                    ('E1','E1  -  機械系           ME'),
                    ('E3','E3  -  化工系           CHE'),
                    ('E4','E4  -  資源系           RE'),
                    ('E5','E5  -  材料系           MSE'),
                    ('E6','E6  -  土木系           CE'),
                    ('E8','E8  -  水利系           HOE'),
                    ('E9','E9  -  工科系           ES'),
                    ('F0','F0  -  能源學程         IBPE'),
                    ('F1','F1  -  系統系           SNME'),
                    ('F4','F4  -  航太系           AA'),
                    ('F5','F5  -  環工系           EV'),
                    ('F6','F6  -  測量系           GM'),
                    ('F9','F9  -  醫工系           BME'),
                    ('H1','H1  -  會計系           ACC'),
                    ('H2','H2  -  統計系           STAT'),
                    ('H3','H3  -  工資系           IIM'),
                    ('H4','H4  -  企管系           BA'),
                    ('H5','H5  -  交管系           TCM'),
                    ('I2','I2  -  護理系           NURS'),
                    ('I3','I3  -  醫技系           MLSB'),
                    ('I5','I5  -  醫學系           MED'),
                    ('I6','I6  -  物治系           PT'),
                    ('I7','I7  -  職治系           OT'),
                    ('I8','I8  -  藥學系           DOPA'),
                    ('D2','D2  -  法律系           LAW'),
                    ('D4','D4  -  政治系           PS'),
                    ('D5','D5  -  經濟系           ECON'),
                    ('D8','D8  -  心理系           PSY'),
                    ('E2','E2  -  電機系           EE'),
                    ('F7','F7  -  資訊系           CSIE'),
                    ('E7','E7  -  建築系           ARCH'),
                    ('F2','F2  -  都計系           UP'),
                    ('F3','F3  -  工設系           ID'),
                    ('C5','C5  -  生科系           LS'),
                    ('C6','C6  -  生技系           BBS'),)

GEC_CHOICE = (('', '---'),
              ('Core GE courses 1', '核心通識向度一'),
              ('Core GE courses 2', '核心通識向度二'),
              ('Core GE courses 3', '核心通識向度三'),
              ('Core GE courses 4', '核心通識向度四'),
              ('Core GE courses 5', '核心通識向度五'),
              ('Core GE courses 6', '核心通識向度六'),
              ('Core GE courses 7', '核心通識向度七'),)

GE_CHOICE = (('', '---'),
             ('Natural Sciences', '自然科學領域'),
             ('Social Sciences', '社會科學領域 '),
             ('Humanities', '人文學領域'),)
